const { SlashCommandBuilder } = require('@discordjs/builders');

var promptchars = ['A PIGMAN', 'A MERM', 'A CATCOON', 'A HOUND', 'A BUNNYMAN', 'A STAGEHAND', 'WORTOX', 'WHEELER', 'WAGSTAFF', 'WILBA', 'WORMWOOD', 'WILSON', 'WILLOW', 'WOLFGANG', 'WENDY', 'ABIGAIL', 'WX-78', 'WICKERBOTTOM', 'WOODIE', 'LUCY THE AXE', 'MAXWELL', 'WILLIAM CARTER', 'WES', 'WIGFRID', 'BERNIE THE TEDDY BEAR',
'WEBBER', 'WALANI', 'WARLY', 'WOODLEGS', 'WILBUR', 'WALTER', 'WOBY', 'CHARLIE', 'WINONA', 'CHESTER', 'HUTCH', 'PACKIM BAGGINS', 'MR. SKITS',  'GLOMMER', 'PUGNA', 'BILLY', 'MUMSY', 'PIPTON', 'SAMMY' ];

var ficpromptwords = [' GET INTO AN ARGUMENT', ' ARE FORCED BY CIRCUMSTANCES TO WORK TOGETHER', ' CUDDLE FOR WARMTH BY A FIREPIT', ' DISCOVER TRACES OF EACH OTHERS\' EXISTENCE AND LEARN THEY ARE NOT ALONE', ' BATTLE SIDE BY SIDE IN THE FORGE', ', IN WHICH ONE RESCUES THE OTHER FROM A SWAMP TENTACLE', ', IN WHICH ONE RESCUES THE OTHER FROM A SPIDER NEST', ' SAILING THE OCEAN TOGETHER AND ARGUING',
' SAIL THE OCEAN TOGETHER AND DISCOVERING BURIED TREASURE', ' SHARE THEIR LAST STORES OF FOOD', ' HUNT A DANGEROUS MONSTER TOGETHER', ' HUNT FOOD TOGETHER', ', IN WHICH ONE LEARNS THE OTHER\'S DEEPEST FEAR', ' WORK TOGETHER TO FARM CROPS', ' ATTEND COLLEGE TOGETHER IN A MODERN AU', ', AFTER ESCAPING THE CONSTANT, REMINISCE WITH EACH OTHER ON THE TIME SPENT THERE', ', IN WHICH ONE WAKES THE OTHER FROM A NIGHTMARE',
' SOLVING CRIMES AS FRIENDLY RIVALS IN A SUPERHERO AU', ', IN WHICH ONE SECRETLY PREPARES A GIFT FOR THE OTHER', ', IN WHICH ONE SUCCESSFULLY REVIVES THE OTHER FROM DEATH FOR THE FIRST TIME', ' EXPLORE THE ANCIENT RUINS TOGETHER', ' ENCOUNTER A TERRORBEAK', ' ARE CAUGHT IN FROG RAIN WHICH INTERRUPTS AN IMPORTANT AND EMOTIONAL CONVERSATION', ' HOST A YOUTUBE LETSPLAY CHANNEL IN A MODERN AU',
', IN WHICH ONE TEACHES THE OTHER A SURVIVAL SKILL', ' TRY TO ONE-UP EACH OTHER WITH SCARY STORIES', ', IN WHICH ONE IS SEATED ON THE NIGHTMARE THRONE AND THE OTHER CONFRONTS THEM', ' GOSSIP AND BRAID EACH OTHERS\' HAIR (OR BRUSH IT, PAINT NAILS, ETC.)', ' BATTLE A GIANT', ' INTERACT BACKSTAGE OUT OF CHARACTER, IN AN AU WHERE THE EVENTS SEEN INGAME ARE FICTIONAL AND THEY ARE ACTORS',
' ADOPT A SMALLBIRD TOGETHER AND ATTEMPT TO RAISE IT', ' DEFACE A STATUE OF MAXWELL TOGETHER', ' PREPARE A FEAST TO CELEBRATE THE END OF WINTER', ' ATTEMPT TO REPAIR A BROKEN OBJECT TOGETHER, DESPITE VERY DIFFERENT IDEAS ON HOW TO DO SO', ' EXCHANGE PRESENTS GIFT OF THE MAGI-STYLE', ', IN WHICH ONE BREAKS AN IMPORTANT POSSESSION OF THE OTHER\'S AND ATTEMPTS TO HIDE THIS FACT', ' IN AN AU WHERE ONE IS A VAMPIRE AND THE OTHER, A WEREWOLF',
' SAIL TO THE LUNAR ISLAND TOGETHER', ' STRIKE UP AN UNLIKELY FRIENDSHIP IN A FLORIST & TATTOO ARTIST AU', ', IN WHICH ONE RESCUES THE OTHER FROM THE OCEAN', ' ATTEMPTING TO SUPPORT EACH OTHER AS THEY ARE GRADUALLY MERMIFIED', ' COMPETE WITH EACH OTHER TO SEE WHO CAN CHOP WOOD FASTEST', ' SPECULATE ABOUT SCIENCE TOGETHER', ' IN WHICH ONE PLAYS A DEVASTATING PRANK ON THE OTHER'];

module.exports = {
  data: new SlashCommandBuilder()
    .setName('ficprompt')
    .setDescription('Randomized story prompts for two characters.')
    .addStringOption(option => option.setName('char1')
      .setDescription('Who is the first character?'))
    .addStringOption(option => option.setName('char2')
      .setDescription('Who is the second character?')),
  async execute(interaction) {
    var char1 = interaction.options.getString('char1');
    var char2 = interaction.options.getString('char2');
    if (!char1){
       char1 = promptchars[Math.floor(Math.random() * promptchars.length)];
    }
    if (!char2){
       char2 = promptchars[Math.floor(Math.random() * promptchars.length)];
    }
    var promptedficwords = ficpromptwords[Math.floor(Math.random() * ficpromptwords.length)];

    await interaction.reply(char1 + " AND " + char2 + promptedficwords)
    .catch(console.error);
  },
};
